# electron.travis

os:
- linux
- osx

dist: trusty

language: node_js

node_js:
# The major number of the Node.js version used by the latest electron version (see http://electronjs.org).    
- "8"

# To disable building on tags. Tags are supposed to begin with 'v' and only containing digits.
branches:
  except:
    - /^v[0-9]/